### ISSUE TITLE
Division by non factors fail

### ISSUE THREAD

**Issue by Timidan** [tintinweb/solidity-shell#18]
divisions like 100/3 always fail

![image](https://user-images.githubusercontent.com/25876969/181915455-2ede3e0e-d3af-472a-b096-1f739b96fef5.png)

**Comment by tintinweb** [comment]
Hi @Timidan,

you have to provide at least one type or else you'll run into a compiler error.

<img width="583" alt="image" src="https://user-images.githubusercontent.com/2865694/182103469-b70b26e5-be9e-47b9-9b69-8afde9c1eaf9.png">

**Comment by Timidan** [comment]
Awesome... Thanks a lot
