### ISSUE TITLE
Global variable block missing from the shell

### ISSUE THREAD

**Issue by shellandbull** [tintinweb/solidity-shell#3]
As the title suggests, it looks like [block and other global variables](https://docs.soliditylang.org/en/v0.8.9/units-and-global-variables.html#block-and-transaction-properties) are missing on this shell 

Here's my console output:

```js
 »  block
[
  {
    component: 'general',
    errorCode: '5172',
    formattedMessage: 'TypeError: Name has to refer to a struct, enum or contract.\n\n',
    message: 'Name has to refer to a struct, enum or contract.',
    severity: 'error',
    sourceLocation: { end: 144, file: '', start: 139 },
    type: 'TypeError'
  }
]
```

Whereas `msg` seems to be there, even though you can refer to it (!?) But just to its internal properties

```js
»  msg
[
  {
    component: 'general',
    errorCode: '5172',
    formattedMessage: 'TypeError: Name has to refer to a struct, enum or contract.\n\n',
    message: 'Name has to refer to a struct, enum or contract.',
    severity: 'error',
    sourceLocation: { end: 142, file: '', start: 139 },
    type: 'TypeError'
  }
]
 »  msg.data
0xdffeadd0
```

**Comment by tintinweb** [comment]
Hi @mariogintili,

`msg` and `block` are magic globals and as such I don't believe they resolve to struct types. This means you can directly reference the member of the globals like `msg.sender`, `block.number`, but you cannot return all of them at once.
