### ISSUE TITLE
Import Statements not working 

### ISSUE THREAD

**Issue by nemani** [tintinweb/solidity-shell#8]
Not sure how to import contracts to interact with. Ends up with following error, tried using relative and absolute paths to the sol file. 

![image](https://user-images.githubusercontent.com/15715894/146383547-5f683594-5436-4b02-9f32-240040ad9d04.png)

**Comment by tintinweb** [comment]
Hey @nemani,

should be working for imports relative to current working `{cwd}` and `{cwd}/node_modules/` with the next release.

happy holidays 🙌 


----

e.g. `@openzeppelin` installed in `cwd` via `npm`
```solidity
🚀 Entering interactive Solidity ^0.8.10 shell. '.help' and '.exit' are your friends.
 »  ℹ️  ganache-mgr: starting temp. ganache instance ...
 »
 »  import "@openzeppelin/contracts/token/ERC20/IERC20.sol"
 »
```

**Comment by nemani** [comment]
great! Looking forward to it!
