### ISSUE TITLE
Localhost doesn't work on MacOS Big Sur 11.6.1

### ISSUE THREAD

**Issue by sjkelleyjr** [tintinweb/solidity-shell#9]
[This line throws](https://github.com/tintinweb/solidity-shell/blob/master/src/handler.js#L460) after a fresh install on Big Sur.  I fixed it by changing the `~/.solidity-shell/.config` `providerUrl` value from `http://localhost:8545` to `http://127.0.0.1:8545`.  I was going to submit a PR, but assumed there might be security implications to this change.  Given it's a one-liner, you can make it if you deem it safe enough :)

**Comment by tintinweb** [comment]
bold move from apple to deprecate `localhost` if that's really the case :D changing it to `127.0.0.1` should be fine (although that'd lock it to IPv4.. but who's using IPv6 on local networks anyways 😂). Thanks for the report!
